### ISSUE TITLE
ノートブックが閲覧できない

### ISSUE THREAD

**Issue by zima-mak** [ALBERT-Inc/blog_nerf#1]
ノートブックのファイルが閲覧できないので, 確認していただけると助かります.

**Comment by ryamauchi** [comment]
わたしの環境では閲覧できています。github 側の問題かもしれません。
時間をおいて再度確認するか、ローカルにノートブックをダウンロードして手元の jupyter で閲覧するかしていただければと思います。

**Comment by ryamauchi** [comment]
HTML バージョンを追加しておきました。
https://github.com/ALBERT-Inc/blog_nerf/blob/master/NeRF.html
