### ISSUE TITLE
DataParallelを使うには

### ISSUE THREAD

**Issue by cv-dote** [ALBERT-Inc/blog_nerf#2]
恐縮なのですが, 再現実装を複数GPUで実行しようと試みています. pytorchのDataParallelを使うための, この実装でのnet(ここではRadianceField?)のインスタンス化がいまいちわからず困っております. お答えいただけると幸いでございます.

**Comment by ryamauchi** [comment]
`NeRF` クラスを以下のように書き換えて

```python
        self.rf_c = nn.DataParallel(RadianceField(L_x=L_x, L_d=L_d), device_ids=[0, 1, 2])  # 使用する GPU id を指定
        self.rf_f = nn.DataParallel(RadianceField(L_x=L_x, L_d=L_d), device_ids=[0, 1, 2])  # 使用する GPU id を指定
```

`loss_func` を `cuda:0` に送ってやると一応動きました。

```python
loss_func.cuda('cuda:0')
```

並列化をまったく想定せずに書いたスクリプトなのでおかしな部分はあるかもですが、参考までに。

**Comment by cv-dote** [comment]
お答えいただきありがとうございます! 参考にさせていただきます.
